version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    groups:
      build-and-test:
        patterns: ['*']
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns: ['*']
